version: '3.3'

services:
  ddcc:
    container_name: ddcc-transactions-mediator
    image: openhie/ddcc-transactions:latest
    environment:
      FHIR_SERVER: 'http://fhir:8080/fhir/'
      MATCHBOX_SERVER: 'http://matchbox:8080/matchbox/fhir/'
    ports:
      - "4321:4321"
    depends_on:
      - fhir
      - matchbox

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.4.1
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.max_page_size=50
      - hapi.fhir.default_page_size=20
    volumes:
      - type: volume
        source: instant
        target: /instant
    # open hapi ports for development
    ports:
      - "9080:8080"
    depends_on:
      - db


  matchbox:
    container_name: matchbox-fhir
    image: eu.gcr.io/fhir-ch/matchbox:v140
    environment:
      - hapi.fhir.implementationguides.0.name=hl7.fhir.uv.sdc
      - hapi.fhir.implementationguides.0.version=2.7.0
      - hapi.fhir.implementationguides.1.name=ihe.mhd.fhir
      - hapi.fhir.implementationguides.1.version=4.0.1
      - hapi.fhir.implementationguides.2.url=https://worldhealthorganization.github.io/ddcc/refs/heads/ddcc-tr/package.tgz
      - hapi.fhir.implementationguides.2.name=fhir.who.ddcc-vs
      - hapi.fhir.implementationguides.2.version=0.3.1
    volumes:
      - type: volume
        source: instant
        target: /instant
    # open matchbox ports for development
    ports:
      - "9081:8080"

  db:
    container_name: hapi-postgres
    image: postgres
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'instant101'
    volumes:
      - 'hapi-postgres:/var/lib/postgresql'

volumes:
  hapi-postgres:
  instant:

