version: '3.3'

services:
  ddcc:
    container_name: ddcc-transactions-mediator
    image: openhie/ddcc-transactions:latest
    environment:
      FHIR_SERVER: 'http://fhir:8080/fhir/'
      MATCHBOX_SERVER: 'http://matchbox:8080/matchbox/fhir/'
    ports:
      - "4321:4321"
    depends_on:
      - fhir
      - matchbox

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.4.1
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.max_page_size=50
      - hapi.fhir.default_page_size=20
    volumes:
      - type: volume
        source: instant
        target: /instant
    depends_on:
      - db

  matchbox:
    container_name: matchbox-fhir
    image: eu.gcr.io/fhir-ch/matchbox:v140
    environment:
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_SDC_NAME=hl7.fhir.uv.sdc
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_SDC_VERSION=2.7.0
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_MHD_NAME=ihe.mhd.fhir
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_MHD_VERSION=4.0.1
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_DDCC_URL=https://worldhealthorganization.github.io/ddcc/package.tgz
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_DDCC_NAME=fhir.who.ddcc-vs
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_DDCC_VERSION=0.3.1
  db:
    container_name: hapi-postgres
    image: postgres
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'instant101'
    volumes:
      - 'hapi-postgres:/var/lib/postgresql'

volumes:
  hapi-postgres:
  instant:

