version: '3.3'

services:
  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.4.1
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.max_page_size=50
      - hapi.fhir.default_page_size=20
    volumes:
      - type: volume
        source: instant
        target: /instant
    # open hapi ports for development
    ports:
      - "8081:8080"
    depends_on:
      - db


  matchbox:
    container_name: matchbox-fhir
    image: eu.gcr.io/fhir-ch/matchbox:v210
    environment:
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_SDC_NAME=hl7.fhir.uv.sdc
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_SDC_VERSION=2.7.0
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_MHD_NAME=ihe.mhd.fhir
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_MHD_VERSION=4.0.1
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_DDCC_URL=https://worldhealthorganization.github.io/ddcc/package.tgz
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_DDCC_NAME=fhir.who.ddcc
      - HAPI_FHIR_IMPLEMENTATIONGUIDES_DDCC_VERSION=1.0.0
    volumes:
      - type: volume
        source: instant
        target: /instant
    # open matchbox ports for development
    ports:
      - "8080:8080"

  db:
    container_name: hapi-postgres
    image: postgres
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'instant101'
    volumes:
      - 'hapi-postgres:/var/lib/postgresql'

volumes:
  hapi-postgres:
  instant:

